### ISSUE TITLE
Senior Referee rank not colored properly on staff page

### ISSUE THREAD

**Issue by stormer1267** [StratusNetwork/Issues#134] opened 2017-12-01 08:44 UTC
<img width="343" alt="schermafbeelding 2017-12-01 om 09 40 55" src="https://user-images.githubusercontent.com/9406252/33474663-e2ef39cc-d67b-11e7-9804-91b9ae75671e.png">

https://stratus.network/staff

**Comment by Szboy** [comment] 2017-12-01 13:13
This is caused by the dummy group of senior event staff not having a badge, as we use badge_color to color the staff page. The issue however will be fixed in a future larger-scale update.

**Closed as completed** 2018-05-09 15:36 UTC
Labels: Scope: Web
