### ISSUE TITLE
Using item switch key (F) isn't filtered

### ISSUE THREAD

**Issue by Marcono1234** [StratusNetwork/Issues#57] opened 2017-06-27 13:47 UTC
# The bug
If you have your pickaxe in your offhand while moving out of spawn on Verlate it is not cleared.

**Note:** Putting your sword in the 3rd slot will remove it instead.

**Comment by mitchts** [comment] 2017-06-28 04:27
How are you moving it to the off-hand slot..? It's locked to that slot so it shouldn't be able to be moved.

**Comment by Marcono1234** [comment] 2017-06-28 15:31
If I remember it correctly you could use the swap hands key (default `F`).

**Comment by Pablete1234** [comment] 2017-06-28 22:10
The issue is just that pressing "f" should be denied if the item is locked to a slot, has been an issue since 1.9

**Closed as completed** 2019-11-24 19:29 UTC
Labels: Type: Bug, Scope: Server
