### ISSUE TITLE
Lobby isn't pruned

### ISSUE THREAD

**Issue by jexeI** [StratusNetwork/Issues#107] opened 2017-10-01 16:31 UTC
![2017-10-01_11 31 01](https://user-images.githubusercontent.com/8964867/31056720-0dc35a08-a69c-11e7-9e6a-9775bc3cf5c4.png)

**Comment by Szboy** [comment] 2017-10-01 16:49
Duplicate of #74

**Closed as completed by Szboy** 2017-10-01 16:49 UTC
